version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  dart-backend:
    build: ./backend-dart
    depends_on:
      - db
    ports:
      - "8081:8080"

  node-backend:
    build: ./backend-node
    depends_on:
      - db
    ports:
      - "8082:8080"
